site_name: US ATLAS Analysis Facilities Test Site
docs_dir: tier3docs
site_dir: site
extra_javascript:
- scripts/readMoreOrLess.js
plugins:
  - include-markdown
nav:
    - 'Getting Started':
        - 'Introduction': README.md
        - 'Getting Help': GettingHelp.md
    - 'User Onboarding':
        - 'About the Facilities': UserOnboarding/facility.md
        - 'Points of Contact': UserOnboarding/contact.md
        - 'Applying for User Accounts': UserOnboarding/account.md
    - 'Data Store, Accessing and Sharing':
        - 'Data Storage at BNL': doma/storage/BNL/storage-at-bnl.md
        - 'Using Xcache at BNL': doma/Xcache/BNL/Using-Xcache-at-BNL.md
        - 'Data Sharing': doma/DataSharing/README.md
    - 'Jupyter at Analysis Facilities':
        - 'Introduction': jupyter/JupyterAtTier3s.md
        - 'Jupyter at BNL': jupyter/BNLjupyter.md
        - 'Jupyter at SLAC': jupyter/SLACjupyter.md
        - 'Extend ATLAS JupyterLab at SLAC': jupyter/SLACJupyterExtraFuncs.md
        - 'How to get information about an xAOD in python': jupyter/examples/xAODcheck.md
        - 'Read xAODs using PyROOT': https://github.com/usatlas/tier3docs/blob/master/jupyter/examples/pyROOT_example.ipynb
        - 'Info about uproot and xAOD': jupyter/examples/convert_specific_variables.py.txt
    - 'Data Analysis Tutorial (2019-08)':
        - 'Introduction': Tutorial-2019Aug/README.md
        - 'Tutorial of Analysis Examples at BNL': Tutorial-2019Aug/BNL/README.md
        - 'Tutorial of Analysis Examples at SLAC': Tutorial-2019Aug/SLAC/README.md
        - 'Tutorial of Analysis Examples on the Grid': Tutorial-2019Aug/Grid/README.md
    - 'Containers':
        - 'Using Singularity Containers': Containers/UsingSingularity/README.md
    - 'FAQs/Tips':
        - 'FAQs and some tips': faqs-tips/faq-tips.md
theme: 
  name: readthedocs
# more options: https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs
